version: "3.8"

networks:
  docknode-apt:
    driver: bridge

volumes:
  fullnode_data: {}
  caddy_data: {}
  caddy_config: {}

services:
  fullnode:
    image: "aptoslabs/validator:mainnet"
    container_name: fullnode
    hostname: fullnode
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080
      - 9101:9101
      - 6180:6180
    volumes:
      - ./aptos:/opt/aptos/etc
      - fullnode_data:/opt/aptos/data
    command: aptos-node -f /opt/aptos/etc/fullnode.yaml
    networks:
      - docknode-apt

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    container_name: nodeexporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - docknode-apt

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - executionnode
      - beaconnode
      - nodeexporter
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - BASIC_AUTH_USERS=${BASIC_AUTH_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-apt